<a href="https://colab.research.google.com/github/SahithReddy-GitHub/Pneumonia-Detection-Using-CNN/blob/main/CNN_PNEUMONIA_256X256.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Model :- CNN <br>
Filters :- [16,32,64,64,128] <br>
Total Data :- 5850  <br>
Image_size :- 256x256  <br>
Epochs  :- 30  <br>
loss: 0.5792 - accuracy: 0.7344 - val_loss: 0.5972 - val_accuracy: 0.7162

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

import tensorflow as tf
from tensorflow.keras import models, layers
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [2]:
normal_train_path = r"/content/drive/MyDrive/Resized_Data/R_NORMAL_Gray_1341_train"
normal_train_img = os.listdir(normal_train_path)

normal_train = []
for img in normal_train_img:
  input_img = cv2.imread(normal_train_path+ '/' + img,0)
  # ref = cv2.resize(input_img,(256,256))
  normal_train.append(input_img)
print("shape",np.shape(normal_train))

normal_train_array = np.array(normal_train)
print(normal_train_array[0])
normal_train_array = normal_train_array.astype('float32')

normal_train_array /= 255
print(normal_train_array[0])
normal_train_array.shape

shape (1341, 256, 256)
[[ 0  0  0 ... 57 57 57]
 [ 2  3  3 ... 61 62 62]
 [10 10 10 ... 66 68 69]
 ...
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  1]
 [ 0  0  0 ...  0  0  1]]
[[0.         0.         0.         ... 0.22352941 0.22352941 0.22352941]
 [0.00784314 0.01176471 0.01176471 ... 0.23921569 0.24313726 0.24313726]
 [0.03921569 0.03921569 0.03921569 ... 0.25882354 0.26666668 0.27058825]
 ...
 [0.         0.         0.         ... 0.         0.         0.00392157]
 [0.         0.         0.         ... 0.         0.         0.00392157]
 [0.         0.         0.         ... 0.         0.         0.00392157]]


(1341, 256, 256)

In [3]:
pneumonic_train_path = r"/content/drive/MyDrive/Resized_Data/R_PNEUMONIA_Gray_3875_train"
pneumonic_train_img = os.listdir(pneumonic_train_path)

pneumonic_train = []
for img in pneumonic_train_img:
  input_img = cv2.imread(pneumonic_train_path+ '/' + img,0)
  # ref = cv2.resize(input_img,(256,256))
  pneumonic_train.append(input_img)
print("shape",np.shape(pneumonic_train))

pneumonic_train_array = np.array(pneumonic_train)
pneumonic_train_array = pneumonic_train_array.astype('float32')

pneumonic_train_array /= 255
pneumonic_train_array.shape

shape (3885, 256, 256)


(3885, 256, 256)

In [4]:
normal_test_path = r"/content/drive/MyDrive/Resized_Data/R_NORMAL_Gray_234_test"
normal_test_img = os.listdir(normal_test_path)

normal_test = []
for img in normal_test_img:
  input_img = cv2.imread(normal_test_path+ '/' + img,0)
  # ref = cv2.resize(input_img,(256,256))
  normal_test.append(input_img)
print("shape",np.shape(normal_test))

normal_test_array = np.array(normal_test)
normal_test_array = normal_test_array.astype('float32')

normal_test_array /= 255
normal_test_array.shape

shape (234, 256, 256)


(234, 256, 256)

In [5]:
pneumonic_test_path = r"/content/drive/MyDrive/Resized_Data/R_PNEUMONIA_Gray_390_test"
pneumonic_test_img = os.listdir(pneumonic_test_path)

pneumonic_test = []
for img in pneumonic_test_img:
  input_img = cv2.imread(pneumonic_test_path+ '/' + img,0)
  # ref = cv2.resize(input_img,(256,256))
  pneumonic_test.append(input_img)
print("shape",np.shape(pneumonic_test))

pneumonic_test_array = np.array(pneumonic_test)
pneumonic_test_array = pneumonic_test_array.astype('float32')

pneumonic_test_array /= 255
pneumonic_test_array.shape

shape (390, 256, 256)


(390, 256, 256)

In [6]:
x = np.vstack((normal_train_array,normal_test_array,pneumonic_train_array,pneumonic_test_array))

In [7]:
x.shape

(5850, 256, 256)

In [8]:
x = np.expand_dims(x,axis=3)
x.shape

(5850, 256, 256, 1)

In [9]:
y = [0]*(normal_train_array.shape[0]+normal_test_array.shape[0]) + [1]*(pneumonic_test_array.shape[0]+pneumonic_train_array.shape[0])
y = np.array(y)
from keras.utils import to_categorical
y= to_categorical(y)
print(len(y))

5850


In [10]:
y[0]

array([1., 0.], dtype=float32)

In [11]:
y[1574:]

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [12]:
x,y = shuffle(x,y, random_state=3)

In [13]:
### crashing 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=32)

In [14]:
x_train.shape
x_test.shape

(1170, 256, 256, 1)

In [15]:
img_rows, img_cols = 256,256
input_shape = (img_rows, img_cols, 1)

In [16]:
filter = [16,32,64,64,128]

In [17]:
model = Sequential()
model.add(Conv2D(input_shape=(256,256,1),filters=filter[0],kernel_size=(3,3),padding="same", activation="relu"))
model.add(Conv2D(filters=filter[0],kernel_size=(3,3),padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=None))

model.add(Conv2D(filters=filter[1], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[1], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[1], kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=None))

model.add(Conv2D(filters=filter[2], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[2], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[2], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[2], kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=None))

model.add(Conv2D(filters=filter[3], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[3], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[3], kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=None))

model.add(Conv2D(filters=filter[4], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[4], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[4], kernel_size=(3,3), padding="same", activation="relu"))
model.add(Conv2D(filters=filter[4], kernel_size=(3,3), padding="same", activation="relu"))
model.add(MaxPool2D(pool_size=(2,2),strides=None))

# model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
# model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
# model.add(Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"))
# model.add(MaxPool2D(pool_size=(2,2),strides=None))

In [18]:
model.add(Flatten())
model.add(Dense(units=50,activation="relu"))
model.add(Dense(units=50,activation="relu"))
model.add(Dense(units=2, activation="softmax"))

# model.add(Dense(units=50,activation="relu"))
# model.add(Dense(units=50,activation="relu"))


In [19]:
from tensorflow.keras.optimizers import Adam
opt = Adam(learning_rate=0.002)
model.compile(optimizer=opt, loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 256, 256, 16)      160       
                                                                 
 conv2d_1 (Conv2D)           (None, 256, 256, 16)      2320      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 128, 128, 16)     0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 128, 128, 32)      4640      
                                                                 
 conv2d_3 (Conv2D)           (None, 128, 128, 32)      9248      
                                                                 
 conv2d_4 (Conv2D)           (None, 128, 128, 32)      9248      
                                                        

In [21]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5)

Epoch 1/5
147/147 [==============================] - 1379s 9s/step - loss: 0.6817 - accuracy: 0.7344 - val_loss: 0.5978 - val_accuracy: 0.7162
Epoch 2/5
147/147 [==============================] - 1373s 9s/step - loss: 0.5817 - accuracy: 0.7344 - val_loss: 0.5976 - val_accuracy: 0.7162
Epoch 3/5
147/147 [==============================] - 1375s 9s/step - loss: 0.5838 - accuracy: 0.7344 - val_loss: 0.5981 - val_accuracy: 0.7162
Epoch 4/5
147/147 [==============================] - 1367s 9s/step - loss: 0.5817 - accuracy: 0.7344 - val_loss: 0.6111 - val_accuracy: 0.7162
Epoch 5/5
147/147 [==============================] - 1367s 9s/step - loss: 0.5811 - accuracy: 0.7344 - val_loss: 0.5989 - val_accuracy: 0.7162


In [22]:
loss, accuracy = model.evaluate(x_test, y_test, verbose=1)

37/37 [==============================] - 80s 2s/step - loss: 0.5989 - accuracy: 0.7162


In [23]:
pred=model.predict(x_test)

37/37 [==============================] - 78s 2s/step
